#ifndef _SIMAE3801_H_
#define _SIMAE3801_H_
//define regs on emif bus
#define PORT0_OUT (*(char volatile xdata*) 0x1ff)
#define PORT1_OUT (*(char volatile xdata*) 0x1fe)
#define PORT2_OUT (*(char volatile xdata*) 0x1fd)
#define PORT3_OUT (*(char volatile xdata*) 0x1fc)
#define PORT0_IN (*(char volatile xdata*) 0x1fb)
#define PORT1_IN (*(char volatile xdata*) 0x1fa)
#define PORT2_IN (*(char volatile xdata*) 0x1f9)
#define PORT3_IN (*(char volatile xdata*) 0x1f8)
#define CCBUS_EN  (*(char volatile xdata *) 0x1f7)
#define I2C_EN  (*(char volatile xdata *) 0x1f6)
#define FLASH_I2C_EN  (*(char volatile xdata *) 0x1f5)
#define SER0_EN (*(char volatile xdata *) 0x1f4)
#define SER1_EN  (*(char volatile xdata *) 0x1f3)
#define T0_SEL  (*(char volatile xdata *) 0x1f2)
#define PORT0_PU  (*(char volatile xdata *) 0x1f1)
#define PORT1_PU  (*(char volatile xdata *) 0x1f0)
#define PORT2_PU  (*(char volatile xdata *) 0x1ef)
#define PORT3_PU  (*(char volatile xdata *) 0x1ee)
#define PORT0_PD  (*(char volatile xdata *) 0x1ed)
#define PORT1_PD  (*(char volatile xdata *) 0x1ec)
#define PORT2_PD  (*(char volatile xdata *) 0x1eb)
#define PORT3_PD  (*(char volatile xdata *) 0x1ea)
#define PAD_DR0 (*(char volatile xdata *) 0x1e9)
#define PAD_DR1 (*(char volatile xdata *) 0x1e8)
#define PAD_DR2 (*(char volatile xdata *) 0x1e7)
#define PAD_DR3 (*(char volatile xdata *) 0x1e6)
#define PAD_SR0 (*(char volatile xdata *) 0x1e5)
#define PAD_SR1 (*(char volatile xdata *) 0x1e4)
#define PAD_SR2 (*(char volatile xdata *) 0x1e3)
#define PAD_SR3 (*(char volatile xdata *) 0x1e2)
#define CLKCPU_ON (*(char volatile xdata *) 0x1e1)
#define CLKPER_ON (*(char volatile xdata *) 0x1e0)
#define ISEL_CLK0 (*(char volatile xdata *) 0x1df)
#define ISEL_CLK1 (*(char volatile xdata *) 0x1ede)
#endif
